# don't want to compile them
[helium]
src.github_tag = "imputnet/helium-linux"
fetch.url = "https://github.com/imputnet/helium-linux/releases/download/$ver/helium-$ver-x86_64_linux.tar.xz"

[neovide]
src.github_tag = "neovide/neovide"
fetch.url = "https://github.com/neovide/neovide/releases/download/nightly/neovide-linux-x86_64.tar.gz"
# neorg
[neorg-interim-ls]
src.git = "https://github.com/benlubas/neorg-interim-ls"
fetch.github = "benlubas/neorg-interim-ls"

[neorg-conceal-wrap]
src.git = "https://github.com/benlubas/neorg-conceal-wrap"
fetch.github = "benlubas/neorg-conceal-wrap"

[neorg-query]
src.git = "https://github.com/benlubas/neorg-query"
fetch.github = "benlubas/neorg-query"

[neorg]
src.git = "https://github.com/benlubas/neorg"
src.branch = "feat/periodic_journals"
fetch.github = "benlubas/neorg"

# neovim plugins
[heirline-components]
src.git = "https://github.com/Zeioth/heirline-components.nvim"
fetch.github = "Zeioth/heirline-components.nvim"

[cyrillic]
src.git = "https://github.com/nativerv/cyrillic.nvim"
fetch.github = "nativerv/cyrillic.nvim"

# canary keyboard layout
[canary]
src.git = "https://github.com/Apsu/Canary"
fetch.github = "Apsu/Canary"

