# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  canary = {
    pname = "canary";
    version = "74b0430d31606ba82ea18faa35fd0fcd400e46bd";
    src = fetchFromGitHub {
      owner = "Apsu";
      repo = "Canary";
      rev = "74b0430d31606ba82ea18faa35fd0fcd400e46bd";
      fetchSubmodules = false;
      sha256 = "sha256-DsNKYwRKT09rHiSDN2lTXAw7hTs5zYfblvOH/xPJEmQ=";
    };
    date = "2025-02-16";
  };
  cyrillic = {
    pname = "cyrillic";
    version = "86186af29eed2af1a069f9e36140d116a2765c80";
    src = fetchFromGitHub {
      owner = "nativerv";
      repo = "cyrillic.nvim";
      rev = "86186af29eed2af1a069f9e36140d116a2765c80";
      fetchSubmodules = false;
      sha256 = "sha256-B2NjvaKJbkih8HLgFAYVqmTuSKAj7XrCBPVoVpYCXXE=";
    };
    date = "2023-07-07";
  };
  heirline-components = {
    pname = "heirline-components";
    version = "5ea9a16286c01b7c36d58c91903d1f8ff0b7ddeb";
    src = fetchFromGitHub {
      owner = "Zeioth";
      repo = "heirline-components.nvim";
      rev = "5ea9a16286c01b7c36d58c91903d1f8ff0b7ddeb";
      fetchSubmodules = false;
      sha256 = "sha256-M86mP8Xr7tIFi9mM8icHWIzbWTR3W2xdSgzXhxNLMj4=";
    };
    date = "2026-02-25";
  };
  helium = {
    pname = "helium";
    version = "0.14.9.1";
    src = fetchurl {
      url = "https://github.com/imputnet/helium-linux/releases/download/0.14.9.1/helium-0.14.9.1-x86_64_linux.tar.xz";
      sha256 = "sha256-BmYX3xKpzVsyxRxmypMpXRnp6+Z5wLcaEY8aEYN+Zz0=";
    };
  };
  neorg = {
    pname = "neorg";
    version = "4189ef69777996420715aaef9351353e78f7104b";
    src = fetchFromGitHub {
      owner = "benlubas";
      repo = "neorg";
      rev = "4189ef69777996420715aaef9351353e78f7104b";
      fetchSubmodules = false;
      sha256 = "sha256-ic8aXxiVhQeTgg4mpOyCwBhWa56beTloCx6MfMIyMxA=";
    };
    date = "2026-04-05";
  };
  neorg-conceal-wrap = {
    pname = "neorg-conceal-wrap";
    version = "447a76e4abf07ccc5eeb8cc3ee5fae241b434f5a";
    src = fetchFromGitHub {
      owner = "benlubas";
      repo = "neorg-conceal-wrap";
      rev = "447a76e4abf07ccc5eeb8cc3ee5fae241b434f5a";
      fetchSubmodules = false;
      sha256 = "sha256-nEYuC5bM+VLSvBscpOC3EWwyVWzTPWDvv1o4tAzHzVU=";
    };
    date = "2025-10-17";
  };
  neorg-interim-ls = {
    pname = "neorg-interim-ls";
    version = "898898f48fe7a2364d99d32f0dfd95dab5f8591f";
    src = fetchFromGitHub {
      owner = "benlubas";
      repo = "neorg-interim-ls";
      rev = "898898f48fe7a2364d99d32f0dfd95dab5f8591f";
      fetchSubmodules = false;
      sha256 = "sha256-R/xxBIHbj8DxgT+79iuAuKTXYPI/IYctrYqsqq50/zo=";
    };
    date = "2026-04-04";
  };
  neorg-query = {
    pname = "neorg-query";
    version = "64955f82bf6107d8ee05ce9c44bb40edd024b601";
    src = fetchFromGitHub {
      owner = "benlubas";
      repo = "neorg-query";
      rev = "64955f82bf6107d8ee05ce9c44bb40edd024b601";
      fetchSubmodules = false;
      sha256 = "sha256-5qmbZbM0A5mZ5OxxeruNuS9o8FfJymIEHPnHwwxQ5FQ=";
    };
    date = "2026-03-23";
  };
}
